stores/UserStore.ts
=> SCRUM-23--TestImage

app/(tabs)/profile/_layout.tsx, app/(tabs)/profile/settings.tsx, components/navigation/SidebarUserProfileComponent.tsx
Отредактирован сайдбар профиля:
- Создан отдельный экран **Настройки**
- **SOS-уведомления** перенесены в Настройки
- раздел **Мои объявления** закомментирован
=> SCRUM-46--add-settings-to-profile-sidebar

components/custom/text/CustomTextComponent.tsx, components/custom/text/SocialLinkInputProps.tsx, components/profile/ViewPetProfileComponent.tsx, components/profile/ViewProfileComponent.tsx
У пользователя убрана возможность отредактировать данные питомца у другого пользователя
- Спрятаны иконки для редактирования профиля питомца, если это не питомец выбранного пользователя
**Дополнительно:** 
- спрятаны иконки для редактирования чужого профиля (до этого клик по ним был просто не активен)
- случайно исправлен обнаруженный баг: кнопка Добавить питомца в профиле появлялась только после обновления
=> SCRUM-36--block-editing-pet-profile-for-other-user-pet

components/custom/buttons/AddCard.tsx, components/profile/ViewProfileComponent.tsx
- Зафиксирована высота карточек питомцев на 260px
- Добавлено сокращение названия породы при ее длине более 2 строк
=> SCRUM-41 fix profile pet card height

components/custom/inputs/FilterSearchAndTagsComponent.tsx, components/custom/menuItem/ListItemWrapper.tsx, components/custom/menuItem/MunuItemWrapper.tsx
поправил, кстати по скролу не уверен что это я сломал, onClick тоже поправил
=> scroll fix

app/(tabs)/search/activities.tsx, components/common/BottomSheetComponent.tsx, components/custom/buttons/CustomLoadingButton.tsx, components/map/FabGroupComponent.tsx, components/search/ArticlesList.tsx, components/search/feed/CreatePost.tsx, components/search/feed/Feed.tsx, components/search/feed/PostItem.tsx, dtos/Interfaces/feed/IPost.ts, dtos/classes/feed/Post.ts, stores/ChatStore.ts, stores/FeedStore.ts
- Доработан общий стиль поста, настроены отступы
- Отредактирован стиль кнопки **создать пост**
=> SCRUM-45 feed: upd postItem style and FAB (create post button) style

app/index.tsx, components/auth/OnboardingCarousel.tsx, components/filter/FilterComponent.tsx, components/profile/ViewPetProfileComponent.tsx, components/profile/ViewProfileComponent.tsx, package-lock.json, package.json
=> minor IOS corrections

components/custom/inputs/CustomOutlineInputText.tsx, components/profile/EditPetProfileComponent.tsx
- На инпут ввода веса питомца поставлено ограничение количества символов - maxLength = 2
- Также установлено ограничение на ввод иных символов
как итог можно ввести только числа от 0 до 99
=> SCRUM-57 add max weight to pet EditPetProfileComponent

components/search/feed/Feed.tsx, components/search/feed/PostComment.tsx, components/search/feed/PostItem.tsx
- Добавлена мемоизация поста в ленте
- Обновлено отображение bottomsheet с комментариями с учетом полученных комментариев
_Не использовался кастомный компонент bottom sheet по причине использования bottom sheet  footer для фиксирования расположения компонента с добавлением комментария_
_нужно будет исправить: отображение нижнего пэддинга у этого компонента при открытии инпута_
=> SCRUM-45-Feed add PostItem memoization and fix bottom sheet with comments visualisation

components/review/ReviewComment.tsx, components/review/ReviewSection.tsx
- Добавлен padding в кнопки Сохранить / Отменить при редактировании отзыва
Дополнительно: поправлены стили отображения отзывов
=> SCRUM-64--Park-fix-edit-review-css

components/custom/complaint/ComplaintModal.tsx, components/review/ReviewComment.tsx, components/review/ReviewSection.tsx, components/search/feed/Feed.tsx, components/search/feed/PostComment.tsx, components/search/feed/PostItem.tsx, stores/MapStore.ts, stores/SearchStore.ts
**По основной задаче:**
- Реализован функционал удаления комментария под постом
- Реализован функционал удаления отзывы под точкой
**Дополнительно:** 
- Реализован функционал жалобы на пост отзывы под точкой
- Реализован функционал жалобы на комментарий под постом (без обращения на бэк)
**Комментарий:**
_Новые задачи в джире заведены:_
- на связь с бэком [по жалобе на комментарий под постом](https://petmapapp.atlassian.net/jira/software/projects/SCRUM/boards/1?assignee=70121%3Acd9e0a32-2b67-44ec-b1d9-5a7416a5b250&selectedIssue=SCRUM-92)
- на реализацию [жалобы на отзыв](https://petmapapp.atlassian.net/jira/software/projects/SCRUM/boards/1?assignee=70121%3Acd9e0a32-2b67-44ec-b1d9-5a7416a5b250&selectedIssue=SCRUM-90) (сначала перепишу компонент SectionReview)
- на реализацию [жалобы на …
=> Scrum 62 Сomments / reviews / posts : delete and complain functionality

components/custom/selectors/CustomDropdownList.tsx, components/custom/selectors/MultiTagDropdown.tsx, locales/en/translation.json, locales/es/translation.json, locales/ru/translation.json
Добавлена локализация в компоненты CustomDropdownList и MultiTagDropdown.
добавлены новые пропсы:
searchPlaceholder?: string; // Плейсхолдер для поисковой строки
nothingToShow?: string; // Сообщение, о том, что теги не найдены
=> Scrum 87  select breed translate

components/search/feed/Feed.tsx, locales/en/translation.json, locales/es/translation.json, locales/ru/translation.json
Добавлен текст об отсутствии комментариев под постом + локализация.
=> SCRUM-85--add text to the bottomsheetcomments when there are no comments

components/map/point/ViewDangerPoint.tsx, components/map/point/ViewUserPoint.tsx, components/review/ReviewComment.tsx, components/review/ReviewSection.tsx, components/review/ReviewSectionOld.tsx
- Старый код ReviewSection на всякий случай сохранила и закомментировала (ReviewSectionOld)
- Удалила возможность редактирования отзыва и пагинацию списка отзывов
=> Scrum 90  review section refactor

components/navigation/SidebarUserProfileComponent.tsx
Временно закомментирована кнопка "Подписаться" в профиле пользователя, чтобы не смущать тестовых пользователей.
Будет возвращена при реализации логики подписок.
=> SCRUM-105--temp remove subscribe button

components/navigation/SidebarUserProfileComponent.tsx
Закомментирована вся область с подписками
=> SCRUM-105--temp remove subscribe controls

components/navigation/SidebarUserProfileComponent.tsx
Временно закомментированы разделы Мои локации и Поддержка
=> SCRUM-105--temp remove mylocations and support

locales/en/translation.json, locales/es/translation.json, locales/ru/translation.json, utils/utils.ts
В профиле убрана "y." у возраста пользователя.
Добавлена утилитарная функция для выбора склонения единицы измерения возраста питомца с учетом локализации.
=> SCRUM-104--add func of choice age unit

components/custom/text/CustomTranslatableText.tsx, components/search/feed/PostComment.tsx
- Добавлены новые пропсы в CustomTranslatableText
- Добавлена логика перевода текста, если оплачен премиум. Код закомментирован, жду обновленного объекта комментария с бэка
=> Scrum 106  PostComments translate by click

components/search/feed/Feed.tsx, components/search/feed/PostItem.tsx
Исправлено обновление счетчика комментариев в обоих вариантах при оставлении комментария:
- в инпуте сразу под постом
- в инпуте под списком комментариев
=> SCRUM-123--Feed-comments fix counter

components/search/feed/PostItem.tsx
- Добавлено реактивное обновление лайков
=> SCRUM-122--Feed fix likes updating

components/profile/ViewProfileComponent.tsx
Если теперь с сервера придет инфа, то отобразится, если нет будет Мальчик ))
=> Scrum 128  pet gender

components/profile/EditProfileComponent.tsx, components/profile/ViewProfileComponent.tsx
отображение всего текстам при view , 
ввод ограничен 500 символами, дальше у пользователя не печатается
=> правка текстового инпута

components/paywall/FullBenefitsTable.tsx, components/paywall/PaywallModal.tsx, components/paywall/SubscriptionRadioButton.tsx
Результаты:
-  Стартовый экран подписки умещается по высоте без прокрутки.
- Добавлен бейдж со скидкой за год
- Добавлена кнопка назад на экране с полным списком преимуществ
- На втором экране настроено постоянное отображение кнопки **Оформить подписку**
=> SCRUM-135 update ui

app/(auth)/sign-in.tsx, app/(auth)/sign-up.mailvalidation.tsx, app/(auth)/sign-up.passwordreset.tsx, app/(auth)/sign-up.tsx, locales/en/translation.json, locales/es/translation.json, locales/ru/translation.json
Добавлены переводы заголовков алертов при регистрации и входе.
Текст алертов приходит с бэка.
=> SCRUM-109--add translation of the alert title in sign-in and sign-up

components/custom/inputs/CustomInputText.tsx
обновлено регулярное выражение с учетом тире, кавычек , точек
для сложных имен:
сокращения типа Jr. - младший
Santa-Maria
Matthew "Bobby" Felton
=> SCRUM-129--Onboarding-fix-form

components/custom/complaint/ComplaintModal.tsx, components/search/feed/PostComment.tsx, stores/SearchStore.ts
Добавлена возможность жаловаться на комментарий
=> SCRUM-81--Feed-comment-menu

components/paywall/StartModalContent.tsx
=> SCRUM-176-PayWall-close-icon

components/map/AdvtComponent.tsx
Добавлена жалоба на прогулку по клику на 3 точки (вызываем меню)
=> SCRUM-91-Complaint-on-walk

components/search/feed/PostItem.tsx
Немного отрефакторила, должно перестать баговать
=> SCRUM-144-Deleting-post-fix
